// ogl/skills.js

// Skill information used by 3EProfiler that was released by WotC under
// the Open Gaming License (OGL). This file however, is not released under
// the OGL (see above).

var abilityKeys = [
  , // zero index undefined.
  'Str',
  'Dex',
  'Con',
  'Int',
  'Wis',
  'Cha'
];

// Defines the key abilities for each set of core skills.
var skillKeys = {
  'acrobatics': 2,
  'appraise': 4,
  'bluff': 6,
  'climb': 1,
  'craft': 4,
  'diplomacy': 6,
  'disable device': 2,
  'disguise': 6,
  'escape artist': 2,
  'fly': 2,
  'handle animal': 6,
  'heal': 5,
  'intimidate': 6,
  'knowledge': 4,
  'linguistics': 4,
  'perception': 5,
  'perform': 6,
  'profession': 5,
  'ride': 2,
  'sense motive': 5,
  'sleight of hand': 2,
  'spellcraft': 4,
  'stealth': 2,
  'survival': 5,
  'swim': 1,
  'use magic device': 6
};

// Defines which skills are class skills for each core class.
var classSkills = {
                           // Bbn Brd Clr Drd Ftr Mnk Pal Rgr Rog Sor Wiz
  'Acrobatics':               [1,  1,  0,  0,  0,  1,  0,  0,  1,  0,  0 ],
  'Appraise':                 [0,  1,  1,  0,  0,  1,  0,  0,  1,  1,  1 ],
  'Bluff':                    [0,  1,  0,  0,  0,  0,  0,  0,  1,  1,  0 ],
  'Climb':                    [1,  1,  0,  1,  1,  1,  0,  1,  1,  0,  0 ],
  'Craft':                    [1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1 ],
  'Diplomacy':                [0,  1,  1,  0,  0,  0,  1,  0,  1,  0,  0 ],
  'Disable Device':           [0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0 ],
  'Disguise':                 [0,  1,  0,  0,  0,  0,  0,  0,  1,  0,  0 ],
  'Escape Artist':            [0,  1,  0,  0,  0,  1,  0,  0,  1,  0,  0 ],
  'Fly':                      [0,  0,  0,  1,  0,  0,  0,  0,  0,  1,  1 ],
  'Handle Animal':            [1,  0,  0,  1,  1,  0,  1,  1,  0,  0,  0 ],
  'Heal':                     [0,  0,  1,  1,  0,  0,  1,  1,  0,  0,  0 ],
  'Intimidate':               [1,  1,  0,  0,  1,  1,  0,  1,  1,  1,  0 ],
  'Knowledge: Arcana':        [0,  1,  1,  0,  0,  0,  0,  0,  0,  1,  1 ],
  'Knowledge: Engineering':   [0,  1,  0,  0,  1,  0,  0,  0,  0,  0,  1 ],
  'Knowledge: Dungeoneering': [0,  1,  0,  0,  1,  0,  0,  1,  1,  0,  1 ],
  'Knowledge: Geography':     [0,  1,  0,  1,  0,  0,  0,  1,  0,  0,  1 ],
  'Knowledge: History':       [0,  1,  1,  0,  0,  1,  0,  0,  0,  0,  1 ],
  'Knowledge: Local':         [0,  1,  0,  0,  0,  0,  0,  0,  1,  0,  1 ],
  'Knowledge: Nature':        [1,  1,  0,  1,  0,  0,  0,  1,  0,  0,  1 ],
  'Knowledge: Nobility':      [0,  1,  1,  0,  0,  0,  1,  0,  0,  0,  1 ],
  'Knowledge: Religion':      [0,  1,  1,  0,  0,  1,  1,  0,  0,  0,  1 ],
  'Knowledge: The Planes':    [0,  1,  1,  0,  0,  0,  0,  0,  0,  0,  1 ],
  'Linguistics':              [0,  1,  1,  0,  0,  0,  0,  0,  1,  0,  1 ],
  'Perception':               [1,  1,  0,  1,  0,  1,  0,  1,  1,  0,  0 ],
  'Perform':                  [0,  1,  0,  0,  0,  1,  0,  0,  1,  0,  0 ],
  'Profession':               [0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1 ],
  'Ride':                     [1,  0,  0,  1,  1,  1,  1,  1,  0,  0,  0 ],
  'Sense Motive':             [0,  1,  1,  0,  0,  1,  1,  0,  1,  0,  0 ],
  'Sleight of Hand':          [0,  1,  0,  0,  0,  0,  0,  0,  1,  0,  0 ],
  'Spellcraft':               [0,  1,  1,  1,  0,  0,  1,  1,  0,  1,  1 ],
  'Stealth':                  [0,  1,  0,  0,  0,  1,  0,  1,  1,  0,  0 ],
  'Survival':                 [1,  0,  0,  1,  1,  0,  0,  1,  0,  0,  0 ],
  'Swim':                     [1,  0,  0,  1,  1,  1,  0,  1,  1,  0,  0 ],
  'Use Magic Device':         [0,  1,  0,  0,  0,  0,  0,  0,  1,  1,  0 ]
};


var skillAttributes = {
                           // Unskilled use   Armor check
  'acrobatics':               [  true,          true         ],
  'appraise':                 [  true,          false        ],
  'bluff':                    [  true,          false        ],
  'climb':                    [  true,          true         ],
  'craft':                    [  true,          false        ],
  'diplomacy':                [  true,          false        ],
  'disable device':           [  false,         true         ],
  'disguise':                 [  true,          false        ],
  'escape artist':            [  true,          true         ],
  'fly':                      [  true,          true         ],
  'handle animal':            [  false,         false        ],
  'heal':                     [  true,          false        ],
  'intimidate':               [  true,          false        ],
  'knowledge:':               [  false,         false        ],
  'linguistics':              [  false,         false        ],
  'perception':               [  true,          false        ],
  'perform':                  [  true,          false        ],
  'profession':               [  false,         false        ],
  'ride':                     [  true,          true         ],
  'sense motive':             [  true,          false        ],
  'sleight of hand':          [  false,         true         ],
  'spellcraft':               [  false,         false        ],
  'stealth':                  [  true,          true         ],
  'survival':                 [  true,          false        ],
  'swim':                     [  true,          true         ],
  'use magic device':         [  false,         false        ]
};

// Now transform the classSkill object to contain a bitset rather than an array.
for (var skill in classSkills)
{
  var cc_code = 0;
  for (var i = 0; i < classSkills[skill].length; i++)
    cc_code = (cc_code << 1) | classSkills[skill][i];
  classSkills[skill] = cc_code;
}

var baseHelpURL = "http://paizo.com/pathfinderRPG/prd/"

// Defines the URL that points to help for each skill, feat, ability, etc.
// NOTE: in cases where there is some overlap in names--like "armor proficiency"
// and "armor proficiency (light)"--the more specific one MUST come first.
var skillsHelpURL = {

  // Skills

  'acrobatics':                baseHelpURL + "skills/acrobatics.html",
  'appraise':                baseHelpURL + "skills/appraise.html",
  'bluff':                   baseHelpURL + "skills/bluff.html",
  'climb':                   baseHelpURL + "skills/climb.html",
  'craft':                   baseHelpURL + "skills/craft.html",
  'diplomacy':               baseHelpURL + "skills/diplomacy.html",
  'disable device':      baseHelpURL + "skills/disableDevice.html",
  'disguise':                baseHelpURL + "skills/disguise.html",
  'escape artist':       baseHelpURL + "skills/escapeArtist.html",
  'fly':                 baseHelpURL + "skills/fly.html",
  'handle animal':       baseHelpURL + "skills/handleAnimal.html",
  'heal':                    baseHelpURL + "skills/heal.html",
  'intimidate':          baseHelpURL + "skills/intimidate.html",
  'knowledge':               baseHelpURL + "skills/knowledge.html",
  'linguistics':                  baseHelpURL + "skills/linguistics.html",
  'perception':       baseHelpURL + "skills/perception.html",
  'perform':                 baseHelpURL + "skills/perform.html",
  'profession':          baseHelpURL + "skills/profession.html",
  'ride':                    baseHelpURL + "skills/ride.html",
  'sense motive':            baseHelpURL + "skills/senseMotive.html",
  'sleight of hand':         baseHelpURL + "skills/sleightOfHand.html",
  'spellcraft':          baseHelpURL + "skills/spellcraft.html",
  'stealth':                    baseHelpURL + "skills/stealth.html",
  'survival':                baseHelpURL + "skills/survival.html",
  'swim':                    baseHelpURL + "skills/swim.html",
  'use magic device':    baseHelpURL + "skills/useMagicDevice.html",
  
  // Feats
  'acrobatic':                          baseHelpURL + 'feats.html#acrobatic',
  'acrobatic steps':                baseHelpURL + 'feats.html#acrobatic-steps',
  'agile':                             baseHelpURL + 'feats.html#agile',
  'agile maneuvers':                baseHelpURL + 'feats.html#agile-maneuvers',
  'alertness':                          baseHelpURL + 'feats.html#alertness',
  'alignment channel':                baseHelpURL + 'feats.html#alignment-channel',
  'animal affinity':                  baseHelpURL + 'feats.html#animal-Affinity',
  'arcane armor training':                baseHelpURL + 'feats.html#arcane-armor-training',
  'arcane armor mastery':                baseHelpURL + 'feats.html#arcane-armor-mastery',
  'arcane strike':                baseHelpURL + 'feats.html#arcane-strike',
  'armor proficiency (heavy)':     baseHelpURL + 'feats.html#armor-Proficiency-Heavy',
  'armor proficiency (light)':     baseHelpURL + 'feats.html#armor-Proficiency-Light',
  'armor proficiency (medium)':    baseHelpURL + 'feats.html#armor-Proficiency-Medium',
  'armor proficiency':             baseHelpURL + 'feats.html#armor-Proficiency-Light',
  'athletic':                           baseHelpURL + 'feats.html#athletic',
  'augment summoning':                baseHelpURL + 'feats.html#augment-Summoning',
  'bleeding critical':                baseHelpURL + 'feats.html#bleeding-critical',
  'blind-fight':                     baseHelpURL + 'feats.html#blind-Fight',
  'blinding critical':                baseHelpURL + 'feats.html#blinding-critical',
  'brew potion':                     baseHelpURL + 'feats.html#brew-Potion',
  'catch off-guard':                baseHelpURL + 'feats.html#catch-off-guard',
  'channel smite':                baseHelpURL + 'feats.html#channel-smite',
  'cleave':                            baseHelpURL + 'feats.html#cleave',
  'combat casting':                   baseHelpURL + 'feats.html#combat-Casting',
  'combat expertise':                 baseHelpURL + 'feats.html#combat-Expertise',
  'combat reflexes':                  baseHelpURL + 'feats.html#combat-Reflexes',
  'command undead':                baseHelpURL + 'feats.html#command-undead',
  'craft magic arms and armor':    baseHelpURL + 'feats.html#craft-Magic-Arms-And-Armor',
  'craft rod':                          baseHelpURL + 'feats.html#craft-Rod',
  'craft staff':                     baseHelpURL + 'feats.html#craft-Staff',
  'craft wand':                      baseHelpURL + 'feats.html#craft-Wand',
  'craft wondrous item':          baseHelpURL + 'feats.html#craft-Wondrous-Item',
  'critical focus':                baseHelpURL + 'feats.html#critical-focus',
  'critical mastery':                baseHelpURL + 'feats.html#critical-mastery',
  'dazzling display':                baseHelpURL + 'feats.html#dazzling-display',
  'deafening critical':                baseHelpURL + 'feats.html#deafening-critical',
  'deceitful':                          baseHelpURL + 'feats.html#deceitful',
  'defensive combat training':                baseHelpURL + 'feats.html#defensive-combat-training',
  'deflect arrows':                   baseHelpURL + 'feats.html#deflect-Arrows',
  'deft hands':                      baseHelpURL + 'feats.html#deft-Hands',
  'diehard':                        baseHelpURL + 'feats.html#diehard',
  'disruptive':                baseHelpURL + 'feats.html#disruptive',
  'diligent':                           baseHelpURL + 'feats.html#diligent',
  'dodge':                             baseHelpURL + 'feats.html#dodge',
  'empower spell':                    baseHelpURL + 'feats.html#empower-Spell',
  'endurance':                          baseHelpURL + 'feats.html#endurance',
  'enlarge spell':                    baseHelpURL + 'feats.html#enlarge-Spell',
  'eschew materials':                 baseHelpURL + 'feats.html#eschew-Materials',
  'exhausting critical':                baseHelpURL + 'feats.html#exhausting-critical',
  'exotic weapon proficiency':     baseHelpURL + 'feats.html#exotic-Weapon-Proficiency',
  'extend spell':                        baseHelpURL + 'feats.html#extend-Spell',
  'extra channel':                baseHelpURL + 'feats.html#extra-channel',
  'extra ki':                baseHelpURL + 'feats.html#extra-ki',
  'extra lay on hands':                baseHelpURL + 'feats.html#extra-lay-on-hands',
  'extra mercy':                baseHelpURL + 'feats.html#extra-mercy',
  'extra performance':                baseHelpURL + 'feats.html#extra-performance',
  'extra rage':                baseHelpURL + 'feats.html#extra-rage',
  'far shot':                           baseHelpURL + 'feats.html#far-Shot',
  'fleet':                baseHelpURL + 'feats.html#fleet',
  'forge ring':                      baseHelpURL + 'feats.html#forge-Ring',
  'gorgons fist':                baseHelpURL + 'feats.html#gorgon-s-fist',
  'great cleave':                        baseHelpURL + 'feats.html#great-Cleave',
  'great fortitude':                  baseHelpURL + 'feats.html#great-Fortitude',
  'greater bull rush':                baseHelpURL + 'feats.html#greater-bull-rush',
  'greater disarm':                baseHelpURL + 'feats.html#greater-disarm',
  'greater feint':                baseHelpURL + 'feats.html#greater-feint',
  'greater grapple':                baseHelpURL + 'feats.html#greater-grapple',
  'greater overrun':                baseHelpURL + 'feats.html#greater-overrun',
  'greater penatrating strike':                baseHelpURL + 'feats.html#greater-penatrating-strike',
  'greater shield focus':                baseHelpURL + 'feats.html#greater-shield-focus',
  'greater spell focus':          baseHelpURL + 'feats.html#greater-Spell-Focus',
  'greater spell penetration':     baseHelpURL + 'feats.html#greater-Spell-Penetration',
  'greater sunder':                baseHelpURL + 'feats.html#greater-sunder',
  'greater trip':                baseHelpURL + 'feats.html#greater-trip',
  'greater two-weapon fighting':   baseHelpURL + 'feats.html#greater-Two-Weapon-Fighting',
  'greater weapon focus':             baseHelpURL + 'feats.html#greater-Weapon-Focus',
  'greater vital strike':                baseHelpURL + 'feats.html#greater-vital-strike',
  'greater weapon specialization': baseHelpURL + 'feats.html#greater-Weapon-Specialization',
  'heighten spell':                   baseHelpURL + 'feats.html#heighten-Spell',
  'improved bull rush':               baseHelpURL + 'feats.html#improved-Bull-Rush',
  'improved channel':                baseHelpURL + 'feats.html#improved-channel',
  'improved counterspell':            baseHelpURL + 'feats.html#improved-Counterspell',
  'improved critical':                baseHelpURL + 'feats.html#improved-Critical',
  'improved disarm':                  baseHelpURL + 'feats.html#improved-Disarm',
  'improved familiar':                baseHelpURL + 'feats.html#improved-Familiar',
  'improved feint':                   baseHelpURL + 'feats.html#improved-Feint',
  'improved grapple':                 baseHelpURL + 'feats.html#improved-Grapple',
  'improved great fortitude':                baseHelpURL + 'feats.html#improved-great-fortitude',
  'improved initiative':          baseHelpURL + 'feats.html#improved-Initiative',
  'improved iron will':                baseHelpURL + 'feats.html#improved-iron-will',
  'improved lightning reflexes':                baseHelpURL + 'feats.html#improved-lightning-reflexes',
  'improved overrun':                 baseHelpURL + 'feats.html#improved-Overrun',
  'improved precise shot':            baseHelpURL + 'feats.html#improved-Precise-Shot',
  'improved shield bash':             baseHelpURL + 'feats.html#improved-Shield-Bash',
  'improved sunder':                  baseHelpURL + 'feats.html#improved-Sunder',
  'improved trip':                    baseHelpURL + 'feats.html#improved-Trip',
  'improved two-weapon fighting':  baseHelpURL + 'feats.html#improved-Two-Weapon-Fighting',
  'improved unarmed strike':      baseHelpURL + 'feats.html#improved-Unarmed-Strike',
  'improved vital strike':                baseHelpURL + 'feats.html#improved-vital-strike',
  'improvised weapon mastery':                baseHelpURL + 'feats.html#improvised-weapon-mastery',
  'intimidating prowess':                baseHelpURL + 'feats.html#intimidating-prowess',
  'investigator':                        baseHelpURL + 'feats.html#investigator',
  'iron will':                          baseHelpURL + 'feats.html#iron-Will',
  'leadership':                      baseHelpURL + 'feats.html#leadership',
  'lightning reflexes':               baseHelpURL + 'feats.html#lightning-Reflexes',
  'lightning stance':                baseHelpURL + 'feats.html#lightning-stance',
  'lunge':                baseHelpURL + 'feats.html#lunge',
  'magical aptitude':                 baseHelpURL + 'feats.html#magical-Aptitude',
  'manyshot':                           baseHelpURL + 'feats.html#manyshot',
  'martial weapon proficiency':    baseHelpURL + 'feats.html#martial-Weapon-Proficiency',
  'master craftsman':                baseHelpURL + 'feats.html#master-craftsman',
  'maximize spell':                   baseHelpURL + 'feats.html#maximize-Spell',
  'medusas wrath':                baseHelpURL + 'feats.html#medusa-s-wrath',
  'mobility':                           baseHelpURL + 'feats.html#mobility',
  'mounted archery':                  baseHelpURL + 'feats.html#mounted-Archery',
  'mounted combat':                   baseHelpURL + 'feats.html#mounted-Combat',
  'natural spell':                    baseHelpURL + 'feats.html#natural-Spell',
  'negotiator':                      baseHelpURL + 'feats.html#negotiator',
  'nimble moves':                baseHelpURL + 'feats.html#nimble-moves',
  'nimble fingers':                   baseHelpURL + 'feats.html#nimble-Fingers',
  'pentatrating strike':                baseHelpURL + 'feats.html#pentatrating-strike',
  'persuasive':                      baseHelpURL + 'feats.html#persuasive',
  'pinpoint targeting':                baseHelpURL + 'feats.html#pinpoint-targeting',
  'point blank shot':                 baseHelpURL + 'feats.html#point-blank-shot',
  'power attack':                        baseHelpURL + 'feats.html#power-Attack',
  'precise shot':                        baseHelpURL + 'feats.html#precise-Shot',
  'quick draw':                      baseHelpURL + 'feats.html#quick-Draw',
  'quicken spell':                    baseHelpURL + 'feats.html#quicken-Spell',
  'rapid reload':                        baseHelpURL + 'feats.html#rapid-Reload',
  'rapid shot':                      baseHelpURL + 'feats.html#rapid-Shot',
  'ride-by attack':                   baseHelpURL + 'feats.html#ride-By-Attack',
  'run':                              baseHelpURL + 'feats.html#run',
  'scorpion style':                baseHelpURL + 'feats.html#scorpion-style',
  'scribe scroll':                    baseHelpURL + 'feats.html#scribe-Scroll',
  'selective channeling':                baseHelpURL + 'feats.html#selective-channeling',
  'self-sufficient':                  baseHelpURL + 'feats.html#self-Sufficient',
  'shatter defenses':                baseHelpURL + 'feats.html#shatter-defenses',
  'shield focus':                baseHelpURL + 'feats.html#shield-focus',
  'shield master':                baseHelpURL + 'feats.html#shield-master',
  'shield proficiency':               baseHelpURL + 'feats.html#shield-Proficiency',
  'shield slam':                baseHelpURL + 'feats.html#shield-slam',
  'shot on the run':                  baseHelpURL + 'feats.html#shot-On-The-Run',
  'sickening critical':                baseHelpURL + 'feats.html#sickening-critical',
  'silent spell':                        baseHelpURL + 'feats.html#silent-Spell',
  'simple weapon proficiency':     baseHelpURL + 'feats.html#simple-Weapon-Proficiency',
  'skill focus':                     baseHelpURL + 'feats.html#skill-Focus',
  'snatch arrows':                    baseHelpURL + 'feats.html#snatch-Arrows',
  'spell focus':                     baseHelpURL + 'feats.html#spell-Focus',
  'spell mastery':                    baseHelpURL + 'feats.html#spell-Mastery',
  'spell penetration':                baseHelpURL + 'feats.html#spell-Penetration',
  'spellbreaker':                baseHelpURL + 'feats.html#spellbreaker',
  'spirited charge':                  baseHelpURL + 'feats.html#spirited-Charge',
  'spring attack':                    baseHelpURL + 'feats.html#spring-Attack',
  'staggering critical':                baseHelpURL + 'feats.html#staggering-critical',
  'stand still':                baseHelpURL + 'feats.html#stand-still',
  'stealthy':                           baseHelpURL + 'feats.html#stealthy',
  'step up':                baseHelpURL + 'feats.html#step-up',
  'still spell':                     baseHelpURL + 'feats.html#still-Spell',
  'strike back':                baseHelpURL + 'feats.html#strike-back',
  'stunning critical':                baseHelpURL + 'feats.html#stunning-critical',
  'stunning fist':                    baseHelpURL + 'feats.html#stunning-Fist',
  'throw anything':                baseHelpURL + 'feats.html#throw-anything',
  'tiring critical':                baseHelpURL + 'feats.html#tiring-critical',
  'toughness':                          baseHelpURL + 'feats.html#toughness',
  'tower shield proficiency':         baseHelpURL + 'feats.html#tower-Shield-Proficiency',
  'turn undead':                baseHelpURL + 'feats.html#turn-undead',
  'track':                             baseHelpURL + 'feats.html#track',
  'trample':                        baseHelpURL + 'feats.html#trample',
  'two-weapon defense':               baseHelpURL + 'feats.html#two-Weapon-Defense',
  'two-weapon fighting':          baseHelpURL + 'feats.html#two-Weapon-Fighting',
  'two-weapon rend':                baseHelpURL + 'feats.html#two-weapon-rend',
  'unseat':                baseHelpURL + 'feats.html#unseat',
  'vital strike':                baseHelpURL + 'feats.html#vital-strike',
  'weapon finesse':                   baseHelpURL + 'feats.html#weapon-Finesse',
  'weapon focus':                        baseHelpURL + 'feats.html#weapon-Focus',
  'weapon specialization':            baseHelpURL + 'feats.html#weapon-Specialization',
  'whirlwind attack':                 baseHelpURL + 'feats.html#whirlwind-Attack',
  'widen spell':                     baseHelpURL + 'feats.html#widen-Spell',
  'wind stance':                baseHelpURL + 'feats.html#wind-stance',

  // Druid special abilities.
  'nature bond'      :        baseHelpURL + "classes/druid.html#nature-bond",
  'animal companion' :        baseHelpURL + "classes/druid.html#animal-companions-184",
  'wild empathy'     :        baseHelpURL + "classes/druid.html#wild-Empathy-druid",
  'orisons'          :       baseHelpURL + "classes/druid.html#orisons",
  'woodland stride'  :       baseHelpURL + "classes/druid.html#woodland-Stride-druid",
  'nature sense'     :        baseHelpURL + "classes/druid.html#nature-Sense",
  'trackless step'   :        baseHelpURL + "classes/druid.html#trackless-Step",
  "resist nature's lure":    baseHelpURL + "classes/druid.html#resist-Nature-s-Lure",
  'wild shape'       :       baseHelpURL + "classes/druid.html#wild-Shape",
  'venom immunity'   :       baseHelpURL + "classes/druid.html#venom-Immunity",
  'a thousand faces' :       baseHelpURL + "classes/druid.html#a-Thousand-Faces",
  'timeless body'    :       baseHelpURL + "classes/druid.html#Timeless-Body",

  // Animal companion abilities.
  'link'             :       baseHelpURL + "classes/druid.html#companions-link",
  'share spells'     :       baseHelpURL + "classes/druid.html#companions-share-Spells",
  'devotion'         :       baseHelpURL + "classes/druid.html#companions-devotion",
  'multiattack'      :       baseHelpURL + "classes/druid.html#companions-multiattack",

  // Ranger special abilities.
  'wild empathy'     :        baseHelpURL + "classes/ranger.html#wild-Empathy-ranger",
  'favored enemy'    :        baseHelpURL + "classes/ranger.html#favored-Enemy",
  'favored terain'   :        baseHelpURL + "classes/ranger.html#favored-terrain",
  'hunters bond'     :        baseHelpURL + "classes/ranger.html#hunter-s-bond",
  'evasion'          :        baseHelpURL + "classes/ranger.html#evasion-ranger",
  'improved evasion'          :        baseHelpURL + "classes/ranger.html#improved-evasion-ranger",
  'quarry'           :        baseHelpURL + "classes/ranger.html#quarry",
  'improved quarry'          :        baseHelpURL + "classes/ranger.html#improved-quarry",
  'combat style'     :        baseHelpURL + "classes/ranger.html#combat-Style-feat",
  // 'improved combat style':   baseHelpURL + "classes/ranger.html#improved-Combat-Style",
  'woodland stride'  :       baseHelpURL + "classes/ranger.html#woodland-Stride-ranger",
  'swift tracker'    :       baseHelpURL + "classes/ranger.html#swift-Tracker",
  // 'combat style mastery':    baseHelpURL + "classes/ranger.html#combat-Style-Mastery",
  'camouflage'       :       baseHelpURL + "classes/ranger.html#camouflage",
  'hide in plain sight':     baseHelpURL + "classes/ranger.html#hide-in-Plain-Sight",
  'master hunter'          :        baseHelpURL + "classes/ranger.html#master-hunter",

  // Rogue special abilities.
  'sneak attack'     :        baseHelpURL + "classes/rogue.html#sneak-Attack",
  'trapfinding'      :        baseHelpURL + "classes/rogue.html#trapfinding",
  'trap sense'       :        baseHelpURL + "classes/rogue.html#trap-Sense",
  'uncanny dodge'    :        baseHelpURL + "classes/rogue.html#uncanny-Dodge-rogue",
  'improved uncanny dodge':  baseHelpURL + "classes/rogue.html#improved-Uncanny-Dodge-rogue",
  'rogue talent'          :        baseHelpURL + "classes/ranger.html#rogue-talents",

  // Wizard special abilities.
  'summon familiar'  :        baseHelpURL + "classes/sorcererWizard.html#Familiars",
  'scribe scroll'    :        baseHelpURL + "classes/sorcererWizard.html#scribe-Scroll",

  '###last one###'   :           ""
};


var spellsHelpURL = {
  // Spells
  "acid arrow":                              baseHelpURL + "spells/acidArrow.html",
  "acid fog":                                baseHelpURL + "spells/acidFog.html",
  "acid splash":                             baseHelpURL + "spells/acidSplash.html",
  "aid":                                     baseHelpURL + "spells/aid.html",
  "air walk":                                baseHelpURL + "spells/airWalk.html",
  "alarm":                                   baseHelpURL + "spells/alarm.html",
  "align weapon":                        baseHelpURL + "spells/alignWeapon.html",
  "alter self":                              baseHelpURL + "spells/alterSelf.html",
  "analyze dweomer":                     baseHelpURL + "spells/analyzeDweomer.html",
  "animal growth":                       baseHelpURL + "spells/animalGrowth.html",
  "animal messenger":                    baseHelpURL + "spells/animalMessenger.html",
  "animal shapes":                       baseHelpURL + "spells/animalShapes.html",
  "animal trance":                       baseHelpURL + "spells/animalTrance.html",
  "animate dead":                        baseHelpURL + "spells/animateDead.html",
  "animate objects":                     baseHelpURL + "spells/animateObjects.html",
  "animate plants":                          baseHelpURL + "spells/animatePlants.html",
  "animate rope":                        baseHelpURL + "spells/animateRope.html",
  "antilife shell":                          baseHelpURL + "spells/antilifeShell.html",
  "antimagic field":                     baseHelpURL + "spells/antimagicField.html",
  "antipathy":                           baseHelpURL + "spells/antipathy.html",
  "antiplant shell":                     baseHelpURL + "spells/antiplantShell.html",
  "arcane eye":                              baseHelpURL + "spells/arcaneEye.html",
  "arcane lock":                             baseHelpURL + "spells/arcaneLock.html",
  "arcane mark":                             baseHelpURL + "spells/arcaneMark.html",
  "arcane sight":                        baseHelpURL + "spells/arcaneSight.html",
  "arcane sight, greater":           baseHelpURL + "spells/arcaneSightGreater.html",
  "astral projection":                   baseHelpURL + "spells/astralProjection.html",
  "atonement":                           baseHelpURL + "spells/atonement.html",
  "augury":                                  baseHelpURL + "spells/augury.html",
  "awaken":                                  baseHelpURL + "spells/awaken.html",
  "baleful polymorph":                   baseHelpURL + "spells/balefulPolymorph.html",
  "bane":                                    baseHelpURL + "spells/bane.html",
  "banishment":                              baseHelpURL + "spells/banishment.html",
  "barkskin":                                baseHelpURL + "spells/barkskin.html",
  "bear's endurance":                    baseHelpURL + "spells/bearsEndurance.html",
  "bear's endurance, mass":              baseHelpURL + "spells/bearsEnduranceMass.html",
  "bestow curse":                        baseHelpURL + "spells/bestowCurse.html",
  "binding":                                 baseHelpURL + "spells/binding.html",
  "black tentacles":                     baseHelpURL + "spells/blackTentacles.html",
  "blade barrier":                       baseHelpURL + "spells/bladeBarrier.html",
  "blasphemy":                           baseHelpURL + "spells/blasphemy.html",
  "bless":                                   baseHelpURL + "spells/bless.html",
  "bless water":                             baseHelpURL + "spells/blessWater.html",
  "bless weapon":                        baseHelpURL + "spells/blessWeapon.html",
  "blight":                                  baseHelpURL + "spells/blight.html",
  "blindness/deafness":                  baseHelpURL + "spells/blindnessDeafness.html",
  "blink":                                   baseHelpURL + "spells/blink.html",
  "blur":                                    baseHelpURL + "spells/blur.html",
  "break enchantment":                   baseHelpURL + "spells/breakEnchantment.html",
  "bull's strength":                     baseHelpURL + "spells/bullsStrength.html",
  "bull's strength, mass":           baseHelpURL + "spells/bullsStrengthMass.html",
  "burning hands":                       baseHelpURL + "spells/burningHands.html",
  "call lightning":                          baseHelpURL + "spells/callLightning.html",
  "call lightning storm":                baseHelpURL + "spells/callLightningStorm.html",
  "calm animals":                        baseHelpURL + "spells/calmAnimals.html",
  "calm emotions":                       baseHelpURL + "spells/calmEmotions.html",
  "cat's grace":                             baseHelpURL + "spells/catsGrace.html",
  "cat's grace, mass":                   baseHelpURL + "spells/catsGraceMass.html",
  "cause fear":                              baseHelpURL + "spells/causeFear.html",
  "chain lightning":                     baseHelpURL + "spells/chainLightning.html",
  "changestaff":                             baseHelpURL + "spells/changestaff.html",
  "chaos hammer":                        baseHelpURL + "spells/chaosHammer.html",
  "charm animal":                        baseHelpURL + "spells/charmAnimal.html",
  "charm monster":                       baseHelpURL + "spells/charmMonster.html",
  "charm monster, mass":                 baseHelpURL + "spells/charmMonsterMass.html",
  "charm person":                        baseHelpURL + "spells/charmPerson.html",
  "chill metal":                             baseHelpURL + "spells/chillMetal.html",
  "chill touch":                             baseHelpURL + "spells/chillTouch.html",
  "circle of death":                     baseHelpURL + "spells/circleofDeath.html",
  "clairaudience/clairvoyance":          baseHelpURL + "spells/clairaudienceClairvoyance.html",
  "clenched fist":                       baseHelpURL + "spells/clenchedFist.html",
  "cloak of chaos":                          baseHelpURL + "spells/cloakofChaos.html",
  "clone":                                   baseHelpURL + "spells/clone.html",
  "cloudkill":                           baseHelpURL + "spells/cloudkill.html",
  "color spray":                             baseHelpURL + "spells/colorSpray.html",
  "command":                                 baseHelpURL + "spells/command.html",
  "command, greater":                    baseHelpURL + "spells/commandGreater.html",
  "command plants":                          baseHelpURL + "spells/commandPlants.html",
  "command undead":                          baseHelpURL + "spells/commandUndead.html",
  "commune":                                 baseHelpURL + "spells/commune.html",
  "commune with nature":                 baseHelpURL + "spells/communewithNature.html",
  "comprehend languages":                baseHelpURL + "spells/comprehendLanguages.html",
  "cone of cold":                        baseHelpURL + "spells/coneofCold.html",
  "confusion":                           baseHelpURL + "spells/confusion.html",
  "confusion, lesser":                   baseHelpURL + "spells/confusionLesser.html",
  "consecrate":                              baseHelpURL + "spells/consecrate.html",
  "contact other plane":                 baseHelpURL + "spells/contactOtherPlane.html",
  "contagion":                           baseHelpURL + "spells/contagion.html",
  "contingency":                             baseHelpURL + "spells/contingency.html",
  "continual flame":                     baseHelpURL + "spells/continualFlame.html",
  "control plants":                          baseHelpURL + "spells/controlPlants.html",
  "control undead":                          baseHelpURL + "spells/controlUndead.html",
  "control water":                       baseHelpURL + "spells/controlWater.html",
  "control weather":                     baseHelpURL + "spells/controlWeather.html",
  "control winds":                       baseHelpURL + "spells/controlWinds.html",
  "create food and water":           baseHelpURL + "spells/createFoodandWater.html",
  "create greater undead":           baseHelpURL + "spells/createGreaterUndead.html",
  "create undead":                       baseHelpURL + "spells/createUndead.html",
  "create water":                        baseHelpURL + "spells/createWater.html",
  "creeping doom":                       baseHelpURL + "spells/creepingDoom.html",
  "crushing despair":                    baseHelpURL + "spells/crushingDespair.html",
  "crushing hand":                       baseHelpURL + "spells/crushingHand.html",
  "cure critical wounds":                baseHelpURL + "spells/cureCriticalWounds.html",
  "cure critical wounds, mass":          baseHelpURL + "spells/cureCriticalWoundsMass.html",
  "cure light wounds":                   baseHelpURL + "spells/cureLightWounds.html",
  "cure light wounds, mass":             baseHelpURL + "spells/cureLightWoundsMass.html",
  "cure minor wounds":                   baseHelpURL + "spells/cureMinorWounds.html",
  "cure moderate wounds":                baseHelpURL + "spells/cureModerateWounds.html",
  "cure moderate wounds, mass":          baseHelpURL + "spells/cureModerateWoundsMass.html",
  "cure serious wounds":                 baseHelpURL + "spells/cureSeriousWounds.html",
  "cure serious wounds, mass":       baseHelpURL + "spells/cureSeriousWoundsMass.html",
  "curse water":                             baseHelpURL + "spells/curseWater.html",
  "dancing lights":                          baseHelpURL + "spells/dancingLights.html",
  "darkness":                                baseHelpURL + "spells/darkness.html",
  "darkvision":                              baseHelpURL + "spells/darkvision.html",
  "daylight":                                baseHelpURL + "spells/daylight.html",
  "daze":                                    baseHelpURL + "spells/daze.html",
  "daze monster":                        baseHelpURL + "spells/dazeMonster.html",
  "death knell":                             baseHelpURL + "spells/deathKnell.html",
  "death ward":                              baseHelpURL + "spells/deathWard.html",
  "deathwatch":                              baseHelpURL + "spells/deathwatch.html",
  "deep slumber":                        baseHelpURL + "spells/deepSlumber.html",
  "deeper darkness":                     baseHelpURL + "spells/deeperDarkness.html",
  "delay poison":                        baseHelpURL + "spells/delayPoison.html",
  "delayed blast fireball":              baseHelpURL + "spells/delayedBlastFireball.html",
  "demand":                                  baseHelpURL + "spells/demand.html",
  "desecrate":                           baseHelpURL + "spells/desecrate.html",
  "destruction":                             baseHelpURL + "spells/destruction.html",
  "detect animals or plants":        baseHelpURL + "spells/detectAnimalsorPlants.html",
  "detect chaos":                        baseHelpURL + "spells/detectChaos.html",
  "detect evil":                             baseHelpURL + "spells/detectEvil.html",
  "detect good":                             baseHelpURL + "spells/detectGood.html",
  "detect law":                              baseHelpURL + "spells/detectLaw.html",
  "detect magic":                        baseHelpURL + "spells/detectMagic.html",
  "detect poison":                       baseHelpURL + "spells/detectPoison.html",
  "detect scrying":                          baseHelpURL + "spells/detectScrying.html",
  "detect secret doors":                 baseHelpURL + "spells/detectSecretDoors.html",
  "detect snares and pits":              baseHelpURL + "spells/detectSnaresandPits.html",
  "detect thoughts":                     baseHelpURL + "spells/detectThoughts.html",
  "detect undead":                       baseHelpURL + "spells/detectUndead.html",
  "dictum":                                  baseHelpURL + "spells/dictum.html",
  "dimension door":                          baseHelpURL + "spells/dimensionDoor.html",
  "dimensional anchor":                  baseHelpURL + "spells/dimensionalAnchor.html",
  "dimensional lock":                    baseHelpURL + "spells/dimensionalLock.html",
  "diminish plants":                     baseHelpURL + "spells/diminishPlants.html",
  "discern lies":                        baseHelpURL + "spells/discernLies.html",
  "discern location":                    baseHelpURL + "spells/discernLocation.html",
  "disguise self":                       baseHelpURL + "spells/disguiseSelf.html",
  "disintegrate":                        baseHelpURL + "spells/disintegrate.html",
  "dismissal":                           baseHelpURL + "spells/dismissal.html",
  "dispel chaos":                        baseHelpURL + "spells/dispelChaos.html",
  "dispel evil":                             baseHelpURL + "spells/dispelEvil.html",
  "dispel good":                             baseHelpURL + "spells/dispelGood.html",
  "dispel law":                              baseHelpURL + "spells/dispelLaw.html",
  "dispel magic":                        baseHelpURL + "spells/dispelMagic.html",
  "dispel magic, greater":           baseHelpURL + "spells/dispelMagicGreater.html",
  "displacement":                        baseHelpURL + "spells/displacement.html",
  "disrupt undead":                          baseHelpURL + "spells/disruptUndead.html",
  "disrupting weapon":                   baseHelpURL + "spells/disruptingWeapon.html",
  "divination":                              baseHelpURL + "spells/divination.html",
  "divine favor":                        baseHelpURL + "spells/divineFavor.html",
  "divine power":                        baseHelpURL + "spells/divinePower.html",
  "dominate animal":                     baseHelpURL + "spells/dominateAnimal.html",
  "dominate monster":                    baseHelpURL + "spells/dominateMonster.html",
  "dominate person":                     baseHelpURL + "spells/dominatePerson.html",
  "doom":                                    baseHelpURL + "spells/doom.html",
  "dream":                                   baseHelpURL + "spells/dream.html",
  "eagle's splendor":                    baseHelpURL + "spells/eaglesSplendor.html",
  "eagle's splendor, mass":              baseHelpURL + "spells/eaglesSplendorMass.html",
  "earthquake":                              baseHelpURL + "spells/earthquake.html",
  "elemental swarm":                     baseHelpURL + "spells/elementalSwarm.html",
  "endure elements":                     baseHelpURL + "spells/endureElements.html",
  "energy drain":                        baseHelpURL + "spells/energyDrain.html",
  "enervation":                              baseHelpURL + "spells/enervation.html",
  "enlarge person":                          baseHelpURL + "spells/enlargePerson.html",
  "enlarge person, mass":                baseHelpURL + "spells/enlargePersonMass.html",
  "entangle":                                baseHelpURL + "spells/entangle.html",
  "enthrall":                                baseHelpURL + "spells/enthrall.html",
  "entropic shield":                     baseHelpURL + "spells/entropicShield.html",
  "erase":                                   baseHelpURL + "spells/erase.html",
  "ethereal jaunt":                          baseHelpURL + "spells/etherealJaunt.html",
  "etherealness":                        baseHelpURL + "spells/etherealness.html",
  "expeditious retreat":                 baseHelpURL + "spells/expeditiousRetreat.html",
  "explosive runes":                     baseHelpURL + "spells/explosiveRunes.html",
  "eyebite":                                 baseHelpURL + "spells/eyebite.html",
  "fabricate":                           baseHelpURL + "spells/fabricate.html",
  "faerie fire":                             baseHelpURL + "spells/faerieFire.html",
  "false life":                              baseHelpURL + "spells/falseLife.html",
  "false vision":                        baseHelpURL + "spells/falseVision.html",
  "fear":                                    baseHelpURL + "spells/fear.html",
  "feather fall":                        baseHelpURL + "spells/featherFall.html",
  "feeblemind":                              baseHelpURL + "spells/feeblemind.html",
  "find the path":                       baseHelpURL + "spells/findthePath.html",
  "find traps":                              baseHelpURL + "spells/findTraps.html",
  "finger of death":                     baseHelpURL + "spells/fingerofDeath.html",
  "fire seeds":                              baseHelpURL + "spells/fireSeeds.html",
  "fire shield":                             baseHelpURL + "spells/fireShield.html",
  "fire storm":                              baseHelpURL + "spells/fireStorm.html",
  "fire trap":                           baseHelpURL + "spells/fireTrap.html",
  "fireball":                                baseHelpURL + "spells/fireball.html",
  "flame arrow":                             baseHelpURL + "spells/flameArrow.html",
  "flame blade":                             baseHelpURL + "spells/flameBlade.html",
  "flame strike":                        baseHelpURL + "spells/flameStrike.html",
  "flaming sphere":                          baseHelpURL + "spells/flamingSphere.html",
  "flare":                                   baseHelpURL + "spells/flare.html",
  "flesh to stone":                          baseHelpURL + "spells/fleshtoStone.html",
  "fly":                                     baseHelpURL + "spells/fly.html",
  "floating disk":                       baseHelpURL + "spells/floatingDisk.html",
  "fog cloud":                           baseHelpURL + "spells/fogCloud.html",
  "forbiddance":                             baseHelpURL + "spells/forbiddance.html",
  "forcecage":                           baseHelpURL + "spells/forcecage.html",
  "forceful hand":                       baseHelpURL + "spells/forcefulHand.html",
  "foresight":                           baseHelpURL + "spells/foresight.html",
  "fox's cunning":                       baseHelpURL + "spells/foxsCunning.html",
  "fox's cunning, mass":                 baseHelpURL + "spells/foxsCunningMass.html",
  "freedom":                                 baseHelpURL + "spells/freedom.html",
  "freedom of movement":                 baseHelpURL + "spells/freedomofMovement.html",
  "freezing sphere":                     baseHelpURL + "spells/freezingSphere.html",
  "gaseous form":                        baseHelpURL + "spells/gaseousForm.html",
  "gate":                                    baseHelpURL + "spells/gate.html",
  "geas/quest":                              baseHelpURL + "spells/geasQuest.html",
  "geas, lesser":                        baseHelpURL + "spells/geasLesser.html",
  "gentle repose":                       baseHelpURL + "spells/gentleRepose.html",
  "ghost sound":                             baseHelpURL + "spells/ghostSound.html",
  "ghoul touch":                             baseHelpURL + "spells/ghoulTouch.html",
  "giant vermin":                        baseHelpURL + "spells/giantVermin.html",
  "glibness":                                baseHelpURL + "spells/glibness.html",
  "glitterdust":                             baseHelpURL + "spells/glitterdust.html",
  "globe of invulnerability":        baseHelpURL + "spells/globeofInvulnerability.html",
  "globe of invulnerability, lesser": baseHelpURL + "spells/globeofInvulnerabilityLesser.html",
  "glyph of warding":                    baseHelpURL + "spells/glyphofWarding.html",
  "glyph of warding, greater":       baseHelpURL + "spells/glyphofWardingGreater.html",
  "goodberry":                           baseHelpURL + "spells/goodberry.html",
  "good hope":                           baseHelpURL + "spells/goodHope.html",
  "grasping hand":                       baseHelpURL + "spells/graspingHand.html",
  "grease":                                  baseHelpURL + "spells/grease.html",
  "greater (spell name)":                baseHelpURL + "spells/greaterSpellName.html",
  "guards and wards":                    baseHelpURL + "spells/guardsandWards.html",
  "guidance":                                baseHelpURL + "spells/guidance.html",
  "gust of wind":                        baseHelpURL + "spells/gustofWind.html",
  "hallow":                                  baseHelpURL + "spells/hallow.html",
  "hallucinatory terrain":           baseHelpURL + "spells/hallucinatoryTerrain.html",
  "halt undead":                             baseHelpURL + "spells/haltUndead.html",
  "harm":                                    baseHelpURL + "spells/harm.html",
  "haste":                                   baseHelpURL + "spells/haste.html",
  "heal":                                    baseHelpURL + "spells/heal.html",
  "heal, mass":                              baseHelpURL + "spells/healMass.html",
  "heal mount":                              baseHelpURL + "spells/healMount.html",
  "heat metal":                              baseHelpURL + "spells/heatMetal.html",
  "helping hand":                        baseHelpURL + "spells/helpingHand.html",
  "heroes' feast":                       baseHelpURL + "spells/heroesFeast.html",
  "heroism":                                 baseHelpURL + "spells/heroism.html",
  "heroism, greater":                    baseHelpURL + "spells/heroismGreater.html",
  "hide from animals":                   baseHelpURL + "spells/hidefromAnimals.html",
  "hide from undead":                    baseHelpURL + "spells/hidefromUndead.html",
  "hideous laughter":                    baseHelpURL + "spells/hideousLaughter.html",
  "hold animal":                             baseHelpURL + "spells/holdAnimal.html",
  "hold monster":                        baseHelpURL + "spells/holdMonster.html",
  "hold monster, mass":                  baseHelpURL + "spells/holdMonsterMass.html",
  "hold person":                             baseHelpURL + "spells/holdPerson.html",
  "hold person, mass":                   baseHelpURL + "spells/holdPersonMass.html",
  "hold portal":                             baseHelpURL + "spells/holdPortal.html",
  "holy aura":                           baseHelpURL + "spells/holyAura.html",
  "holy smite":                              baseHelpURL + "spells/holySmite.html",
  "holy sword":                              baseHelpURL + "spells/holySword.html",
  "holy word":                           baseHelpURL + "spells/holyWord.html",
  "horrid wilting":                          baseHelpURL + "spells/horridWilting.html",
  "hypnotic pattern":                    baseHelpURL + "spells/hypnoticPattern.html",
  "hypnotism":                           baseHelpURL + "spells/hypnotism.html",
  "ice storm":                           baseHelpURL + "spells/iceStorm.html",
  "identify":                                baseHelpURL + "spells/identify.html",
  "illusory script":                     baseHelpURL + "spells/illusoryScript.html",
  "illusory wall":                       baseHelpURL + "spells/illusoryWall.html",
  "imbue with spell ability":        baseHelpURL + "spells/imbuewithSpellAbility.html",
  "implosion":                           baseHelpURL + "spells/implosion.html",
  "imprisonment":                        baseHelpURL + "spells/imprisonment.html",
  "incendiary cloud":                    baseHelpURL + "spells/incendiaryCloud.html",
  "inflict critical wounds":             baseHelpURL + "spells/inflictCriticalWounds.html",
  "inflict critical wounds, mass":    baseHelpURL + "spells/inflictCriticalWoundsMass.html",
  "inflict light wounds":                baseHelpURL + "spells/inflictLightWounds.html",
  "inflict light wounds, mass":          baseHelpURL + "spells/inflictLightWoundsMass.html",
  "inflict minor wounds":                baseHelpURL + "spells/inflictMinorWounds.html",
  "inflict moderate wounds":             baseHelpURL + "spells/inflictModerateWounds.html",
  "inflict moderate wounds, mass":    baseHelpURL + "spells/inflictModerateWoundsMass.html",
  "inflict serious wounds":              baseHelpURL + "spells/inflictSeriousWounds.html",
  "inflict serious wounds, mass":     baseHelpURL + "spells/inflictSeriousWoundsMass.html",
  "insanity":                                baseHelpURL + "spells/insanity.html",
  "insect plague":                       baseHelpURL + "spells/insectPlague.html",
  "instant summons":                     baseHelpURL + "spells/instantSummons.html",
  "interposing hand":                    baseHelpURL + "spells/interposingHand.html",
  "invisibility":                        baseHelpURL + "spells/invisibility.html",
  "invisibility, greater":           baseHelpURL + "spells/invisibilityGreater.html",
  "invisibility, mass":                  baseHelpURL + "spells/invisibilityMass.html",
  "invisibility purge":                  baseHelpURL + "spells/invisibilityPurge.html",
  "invisibility sphere":                 baseHelpURL + "spells/invisibilitySphere.html",
  "iron body":                           baseHelpURL + "spells/ironBody.html",
  "ironwood":                                baseHelpURL + "spells/ironwood.html",
  "irresistible dance":                  baseHelpURL + "spells/irresistibleDance.html",
  "jump":                                    baseHelpURL + "spells/jump.html",
  "keen edge":                           baseHelpURL + "spells/keenEdge.html",
  "knock":                                   baseHelpURL + "spells/knock.html",
  "know direction":                          baseHelpURL + "spells/knowDirection.html",
  "legend lore":                             baseHelpURL + "spells/legendLore.html",
  "lesser (spell name)":                 baseHelpURL + "spells/lesserSpellName.html",
  "levitate":                                baseHelpURL + "spells/levitate.html",
  "light":                                   baseHelpURL + "spells/light.html",
  "lightning bolt":                          baseHelpURL + "spells/lightningBolt.html",
  "limited wish":                        baseHelpURL + "spells/limitedWish.html",
  "liveoak":                                 baseHelpURL + "spells/liveoak.html",
  "locate creature":                     baseHelpURL + "spells/locateCreature.html",
  "locate object":                       baseHelpURL + "spells/locateObject.html",
  "longstrider":                             baseHelpURL + "spells/longstrider.html",
  "lullaby":                                 baseHelpURL + "spells/lullaby.html",
  "mage armor":                              baseHelpURL + "spells/mageArmor.html",
  "mage hand":                           baseHelpURL + "spells/mageHand.html",
  "mage's disjunction":                  baseHelpURL + "spells/magesDisjunction.html",
  "mage's faithful hound":           baseHelpURL + "spells/magesFaithfulHound.html",
  "mage's lucubration":                  baseHelpURL + "spells/magesLucubration.html",
  "mage's magnificent mansion":          baseHelpURL + "spells/magesMagnificentMansion.html",
  "mage's private sanctum":              baseHelpURL + "spells/magesPrivateSanctum.html",
  "mage's sword":                        baseHelpURL + "spells/magesSword.html",
  "magic aura":                              baseHelpURL + "spells/magicAura.html",
  "magic circle against chaos":          baseHelpURL + "spells/magicCircleagainstChaos.html",
  "magic circle against evil":       baseHelpURL + "spells/magicCircleagainstEvil.html",
  "magic circle against good":       baseHelpURL + "spells/magicCircleagainstGood.html",
  "magic circle against law":        baseHelpURL + "spells/magicCircleagainstLaw.html",
  "magic fang":                              baseHelpURL + "spells/magicFang.html",
  "magic fang, greater":                 baseHelpURL + "spells/magicFangGreater.html",
  "magic jar":                           baseHelpURL + "spells/magicJar.html",
  "magic missile":                       baseHelpURL + "spells/magicMissile.html",
  "magic mouth":                             baseHelpURL + "spells/magicMouth.html",
  "magic stone":                             baseHelpURL + "spells/magicStone.html",
  "magic vestment":                          baseHelpURL + "spells/magicVestment.html",
  "magic weapon":                        baseHelpURL + "spells/magicWeapon.html",
  "magic weapon, greater":           baseHelpURL + "spells/magicWeaponGreater.html",
  "major creation":                          baseHelpURL + "spells/majorCreation.html",
  "major image":                             baseHelpURL + "spells/majorImage.html",
  "make whole":                              baseHelpURL + "spells/makeWhole.html",
  "mark of justice":                     baseHelpURL + "spells/markofJustice.html",
  "mass (spell name)":                   baseHelpURL + "spells/massSpellName.html",
  "maze":                                    baseHelpURL + "spells/maze.html",
  "meld into stone":                     baseHelpURL + "spells/meldintoStone.html",
  "mending":                                 baseHelpURL + "spells/mending.html",
  "message":                                 baseHelpURL + "spells/message.html",
  "meteor swarm":                        baseHelpURL + "spells/meteorSwarm.html",
  "mind blank":                              baseHelpURL + "spells/mindBlank.html",
  "mind fog":                                baseHelpURL + "spells/mindFog.html",
  "minor creation":                          baseHelpURL + "spells/minorCreation.html",
  "minor image":                             baseHelpURL + "spells/minorImage.html",
  "miracle":                                 baseHelpURL + "spells/miracle.html",
  "mirage arcana":                       baseHelpURL + "spells/mirageArcana.html",
  "mirror image":                        baseHelpURL + "spells/mirrorImage.html",
  "misdirection":                        baseHelpURL + "spells/misdirection.html",
  "mislead":                                 baseHelpURL + "spells/mislead.html",
  "mnemonic enhancer":                   baseHelpURL + "spells/mnemonicEnhancer.html",
  "modify memory":                       baseHelpURL + "spells/modifyMemory.html",
  "moment of prescience":                baseHelpURL + "spells/momentofPrescience.html",
  "mount":                                   baseHelpURL + "spells/mount.html",
  "move earth":                              baseHelpURL + "spells/moveEarth.html",
  "neutralize poison":                   baseHelpURL + "spells/neutralizePoison.html",
  "nightmare":                           baseHelpURL + "spells/nightmare.html",
  "nondetection":                        baseHelpURL + "spells/nondetection.html",
  "obscure object":                          baseHelpURL + "spells/obscureObject.html",
  "obscuring mist":                          baseHelpURL + "spells/obscuringMist.html",
  "open/close":                              baseHelpURL + "spells/openClose.html",
  "order's wrath":                       baseHelpURL + "spells/ordersWrath.html",
  "overland flight":                     baseHelpURL + "spells/overlandFlight.html",
  "owl's wisdom":                        baseHelpURL + "spells/owlsWisdom.html",
  "owl's wisdom, mass":                  baseHelpURL + "spells/owlsWisdomMass.html",
  "passwall":                                baseHelpURL + "spells/passwall.html",
  "pass without trace":                  baseHelpURL + "spells/passwithoutTrace.html",
  "permanency":                              baseHelpURL + "spells/permanency.html",
  "permanent image":                     baseHelpURL + "spells/permanentImage.html",
  "persistent image":                    baseHelpURL + "spells/persistentImage.html",
  "phantasmal killer":                   baseHelpURL + "spells/phantasmalKiller.html",
  "phantom steed":                       baseHelpURL + "spells/phantomSteed.html",
  "phantom trap":                        baseHelpURL + "spells/phantomTrap.html",
  "phase door":                              baseHelpURL + "spells/phaseDoor.html",
  "planar ally":                             baseHelpURL + "spells/planarAlly.html",
  "planar ally, greater":                baseHelpURL + "spells/planarAllyGreater.html",
  "planar ally, lesser":                 baseHelpURL + "spells/planarAllyLesser.html",
  "planar binding":                          baseHelpURL + "spells/planarBinding.html",
  "planar binding, greater":             baseHelpURL + "spells/planarBindingGreater.html",
  "planar binding, lesser":              baseHelpURL + "spells/planarBindingLesser.html",
  "plane shift":                             baseHelpURL + "spells/planeShift.html",
  "plant growth":                        baseHelpURL + "spells/plantGrowth.html",
  "poison":                                  baseHelpURL + "spells/poison.html",
  "polar ray":                           baseHelpURL + "spells/polarRay.html",
  "polymorph":                           baseHelpURL + "spells/polymorph.html",
  "polymorph any object":                baseHelpURL + "spells/polymorphAnyObject.html",
  "power word blind":                    baseHelpURL + "spells/powerWordBlind.html",
  "power word kill":                     baseHelpURL + "spells/powerWordKill.html",
  "power word stun":                     baseHelpURL + "spells/powerWordStun.html",
  "prayer":                                  baseHelpURL + "spells/prayer.html",
  "prestidigitation":                    baseHelpURL + "spells/prestidigitation.html",
  "prismatic sphere":                    baseHelpURL + "spells/prismaticSphere.html",
  "prismatic spray":                     baseHelpURL + "spells/prismaticSpray.html",
  "prismatic wall":                          baseHelpURL + "spells/prismaticWall.html",
  "produce flame":                       baseHelpURL + "spells/produceFlame.html",
  "programmed image":                    baseHelpURL + "spells/programmedImage.html",
  "project image":                       baseHelpURL + "spells/projectImage.html",
  "protection from arrows":              baseHelpURL + "spells/protectionfromArrows.html",
  "protection from chaos":           baseHelpURL + "spells/protectionfromChaos.html",
  "protection from energy":              baseHelpURL + "spells/protectionfromEnergy.html",
  "protection from evil":                baseHelpURL + "spells/protectionfromEvil.html",
  "protection from good":                baseHelpURL + "spells/protectionfromGood.html",
  "protection from law":                 baseHelpURL + "spells/protectionfromLaw.html",
  "protection from spells":              baseHelpURL + "spells/protectionfromSpells.html",
  "prying eyes":                             baseHelpURL + "spells/pryingEyes.html",
  "prying eyes, greater":                baseHelpURL + "spells/pryingEyesGreater.html",
  "purify food and drink":           baseHelpURL + "spells/purifyFoodandDrink.html",
  "pyrotechnics":                        baseHelpURL + "spells/pyrotechnics.html",
  "quench":                                  baseHelpURL + "spells/quench.html",
  "rage":                                    baseHelpURL + "spells/rage.html",
  "rainbow pattern":                     baseHelpURL + "spells/rainbowPattern.html",
  "raise dead":                              baseHelpURL + "spells/raiseDead.html",
  "ray of enfeeblement":                 baseHelpURL + "spells/rayofEnfeeblement.html",
  "ray of exhaustion":                   baseHelpURL + "spells/rayofExhaustion.html",
  "ray of frost":                        baseHelpURL + "spells/rayofFrost.html",
  "read magic":                              baseHelpURL + "spells/readMagic.html",
  "reduce animal":                       baseHelpURL + "spells/reduceAnimal.html",
  "reduce person":                       baseHelpURL + "spells/reducePerson.html",
  "reduce person, mass":                 baseHelpURL + "spells/reducePersonMass.html",
  "refuge":                                  baseHelpURL + "spells/refuge.html",
  "regenerate":                              baseHelpURL + "spells/regenerate.html",
  "reincarnate":                             baseHelpURL + "spells/reincarnate.html",
  "remove blindness/deafness":       baseHelpURL + "spells/removeBlindnessDeafness.html",
  "remove curse":                        baseHelpURL + "spells/removeCurse.html",
  "remove disease":                          baseHelpURL + "spells/removeDisease.html",
  "remove fear":                             baseHelpURL + "spells/removeFear.html",
  "remove paralysis":                    baseHelpURL + "spells/removeParalysis.html",
  "repel metal or stone":                baseHelpURL + "spells/repelMetalorStone.html",
  "repel vermin":                        baseHelpURL + "spells/repelVermin.html",
  "repel wood":                              baseHelpURL + "spells/repelWood.html",
  "repulsion":                           baseHelpURL + "spells/repulsion.html",
  "resilient sphere":                    baseHelpURL + "spells/resilientSphere.html",
  "resistance":                              baseHelpURL + "spells/resistance.html",
  "resist energy":                       baseHelpURL + "spells/resistEnergy.html",
  "restoration":                             baseHelpURL + "spells/restoration.html",
  "restoration, greater":                baseHelpURL + "spells/restorationGreater.html",
  "restoration, lesser":                 baseHelpURL + "spells/restorationLesser.html",
  "resurrection":                        baseHelpURL + "spells/resurrection.html",
  "reverse gravity":                     baseHelpURL + "spells/reverseGravity.html",
  "righteous might":                     baseHelpURL + "spells/righteousMight.html",
  "rope trick":                              baseHelpURL + "spells/ropeTrick.html",
  "rusting grasp":                       baseHelpURL + "spells/rustingGrasp.html",
  "sanctuary":                           baseHelpURL + "spells/sanctuary.html",
  "scare":                                   baseHelpURL + "spells/scare.html",
  "scintillating pattern":           baseHelpURL + "spells/scintillatingPattern.html",
  "scorching ray":                       baseHelpURL + "spells/scorchingRay.html",
  "screen":                                  baseHelpURL + "spells/screen.html",
  "scrying":                                 baseHelpURL + "spells/scrying.html",
  "scrying, greater":                    baseHelpURL + "spells/scryingGreater.html",
  "sculpt sound":                        baseHelpURL + "spells/sculptSound.html",
  "searing light":                       baseHelpURL + "spells/searingLight.html",
  "secret chest":                        baseHelpURL + "spells/secretChest.html",
  "secret page":                             baseHelpURL + "spells/secretPage.html",
  "secure shelter":                          baseHelpURL + "spells/secureShelter.html",
  "see invisibility":                    baseHelpURL + "spells/seeInvisibility.html",
  "seeming":                                 baseHelpURL + "spells/seeming.html",
  "sending":                                 baseHelpURL + "spells/sending.html",
  "sepia snake sigil":                   baseHelpURL + "spells/sepiaSnakeSigil.html",
  "sequester":                           baseHelpURL + "spells/sequester.html",
  "shades":                                  baseHelpURL + "spells/shades.html",
  "shadow conjuration":                  baseHelpURL + "spells/shadowConjuration.html",
  "shadow conjuration, greater":      baseHelpURL + "spells/shadowConjurationGreater.html",
  "shadow evocation":                    baseHelpURL + "spells/shadowEvocation.html",
  "shadow evocation, greater":       baseHelpURL + "spells/shadowEvocationGreater.html",
  "shadow walk":                             baseHelpURL + "spells/shadowWalk.html",
  "shambler":                                baseHelpURL + "spells/shambler.html",
  "shapechange":                             baseHelpURL + "spells/shapechange.html",
  "shatter":                                 baseHelpURL + "spells/shatter.html",
  "shield":                                  baseHelpURL + "spells/shield.html",
  "shield of faith":                     baseHelpURL + "spells/shieldofFaith.html",
  "shield of law":                       baseHelpURL + "spells/shieldofLaw.html",
  "shield other":                        baseHelpURL + "spells/shieldOther.html",
  "shillelagh":                              baseHelpURL + "spells/shillelagh.html",
  "shocking grasp":                          baseHelpURL + "spells/shockingGrasp.html",
  "shout":                                   baseHelpURL + "spells/shout.html",
  "shout, greater":                          baseHelpURL + "spells/shoutGreater.html",
  "shrink item":                             baseHelpURL + "spells/shrinkItem.html",
  "silence":                                 baseHelpURL + "spells/silence.html",
  "silent image":                        baseHelpURL + "spells/silentImage.html",
  "simulacrum":                              baseHelpURL + "spells/simulacrum.html",
  "slay living":                             baseHelpURL + "spells/slayLiving.html",
  "sleep":                                   baseHelpURL + "spells/sleep.html",
  "sleet storm":                             baseHelpURL + "spells/sleetStorm.html",
  "slow":                                    baseHelpURL + "spells/slow.html",
  "snare":                                   baseHelpURL + "spells/snare.html",
  "soften earth and stone":              baseHelpURL + "spells/softenEarthandStone.html",
  "solid fog":                           baseHelpURL + "spells/solidFog.html",
  "song of discord":                     baseHelpURL + "spells/songofDiscord.html",
  "soul bind":                           baseHelpURL + "spells/soulBind.html",
  "sound burst":                             baseHelpURL + "spells/soundBurst.html",
  "speak with animals":                  baseHelpURL + "spells/speakwithAnimals.html",
  "speak with dead":                     baseHelpURL + "spells/speakwithDead.html",
  "speak with plants":                   baseHelpURL + "spells/speakwithPlants.html",
  "spectral hand":                       baseHelpURL + "spells/spectralHand.html",
  "spell immunity":                          baseHelpURL + "spells/spellImmunity.html",
  "spell immunity, greater":             baseHelpURL + "spells/spellImmunityGreater.html",
  "spell resistance":                    baseHelpURL + "spells/spellResistance.html",
  "spellstaff":                              baseHelpURL + "spells/spellstaff.html",
  "spell turning":                       baseHelpURL + "spells/spellTurning.html",
  "spider climb":                        baseHelpURL + "spells/spiderClimb.html",
  "spike growth":                        baseHelpURL + "spells/spikeGrowth.html",
  "spike stones":                        baseHelpURL + "spells/spikeStones.html",
  "spiritual weapon":                    baseHelpURL + "spells/spiritualWeapon.html",
  "statue":                                  baseHelpURL + "spells/statue.html",
  "status":                                  baseHelpURL + "spells/status.html",
  "stinking cloud":                          baseHelpURL + "spells/stinkingCloud.html",
  "stone shape":                             baseHelpURL + "spells/stoneShape.html",
  "stoneskin":                           baseHelpURL + "spells/stoneskin.html",
  "stone tell":                              baseHelpURL + "spells/stoneTell.html",
  "stone to flesh":                          baseHelpURL + "spells/stonetoFlesh.html",
  "storm of vengeance":                  baseHelpURL + "spells/stormofVengeance.html",
  "suggestion":                              baseHelpURL + "spells/suggestion.html",
  "suggestion, mass":                    baseHelpURL + "spells/suggestionMass.html",
  "summon instrument":                   baseHelpURL + "spells/summonInstrument.html",
  "summon monster i":                    baseHelpURL + "spells/summonMonsterI.html",
  "summon monster ii":                   baseHelpURL + "spells/summonMonsterII.html",
  "summon monster iii":                  baseHelpURL + "spells/summonMonsterIII.html",
  "summon monster iv":                   baseHelpURL + "spells/summonMonsterIV.html",
  "summon monster v":                    baseHelpURL + "spells/summonMonsterV.html",
  "summon monster vi":                   baseHelpURL + "spells/summonMonsterVI.html",
  "summon monster vii":                  baseHelpURL + "spells/summonMonsterVII.html",
  "summon monster viii":                 baseHelpURL + "spells/summonMonsterVIII.html",
  "summon monster ix":                   baseHelpURL + "spells/summonMonsterIX.html",
  "summon nature's ally i":              baseHelpURL + "spells/summonNaturesAllyI.html",
  "summon nature's ally ii":             baseHelpURL + "spells/summonNaturesAllyII.html",
  "summon nature's ally iii":        baseHelpURL + "spells/summonNaturesAllyIII.html",
  "summon nature's ally iv":             baseHelpURL + "spells/summonNaturesAllyIV.html",
  "summon nature's ally v":              baseHelpURL + "spells/summonNaturesAllyV.html",
  "summon nature's ally vi":             baseHelpURL + "spells/summonNaturesAllyVI.html",
  "summon nature's ally vii":        baseHelpURL + "spells/summonNaturesAllyVII.html",
  "summon nature's ally viii":       baseHelpURL + "spells/summonNaturesAllyVIII.html",
  "summon nature's ally ix":             baseHelpURL + "spells/summonNaturesAllyIX.html",
  "summon swarm":                        baseHelpURL + "spells/summonSwarm.html",
  "sunbeam":                                 baseHelpURL + "spells/sunbeam.html",
  "sunburst":                                baseHelpURL + "spells/sunburst.html",
  "symbol of death":                     baseHelpURL + "spells/symbolofDeath.html",
  "symbol of fear":                          baseHelpURL + "spells/symbolofFear.html",
  "symbol of insanity":                  baseHelpURL + "spells/symbolofInsanity.html",
  "symbol of pain":                          baseHelpURL + "spells/symbolofPain.html",
  "symbol of persuasion":                baseHelpURL + "spells/symbolofPersuasion.html",
  "symbol of sleep":                     baseHelpURL + "spells/symbolofSleep.html",
  "symbol of stunning":                  baseHelpURL + "spells/symbolofStunning.html",
  "symbol of weakness":                  baseHelpURL + "spells/symbolofWeakness.html",
  "sympathetic vibration":           baseHelpURL + "spells/sympatheticVibration.html",
  "sympathy":                                baseHelpURL + "spells/sympathy.html",
  "telekinesis":                             baseHelpURL + "spells/telekinesis.html",
  "telekinetic sphere":                  baseHelpURL + "spells/telekineticSphere.html",
  "telepathic bond":                     baseHelpURL + "spells/telepathicBond.html",
  "teleport":                                baseHelpURL + "spells/teleport.html",
  "teleport object":                     baseHelpURL + "spells/teleportObject.html",
  "teleport, greater":                   baseHelpURL + "spells/teleportGreater.html",
  "teleportation circle":                baseHelpURL + "spells/teleportationCircle.html",
  "temporal stasis":                     baseHelpURL + "spells/temporalStasis.html",
  "time stop":                           baseHelpURL + "spells/timeStop.html",
  "tiny hut":                                baseHelpURL + "spells/tinyHut.html",
  "tongues":                                 baseHelpURL + "spells/tongues.html",
  "touch of fatigue":                    baseHelpURL + "spells/touchofFatigue.html",
  "touch of idiocy":                     baseHelpURL + "spells/touchofIdiocy.html",
  "transformation":                          baseHelpURL + "spells/transformation.html",
  "transmute metal to wood":             baseHelpURL + "spells/transmuteMetaltoWood.html",
  "transmute mud to rock":           baseHelpURL + "spells/transmuteMudtoRock.html",
  "transmute rock to mud":           baseHelpURL + "spells/transmuteRocktoMud.html",
  "transport via plants":                baseHelpURL + "spells/transportviaPlants.html",
  "trap the soul":                       baseHelpURL + "spells/traptheSoul.html",
  "tree shape":                              baseHelpURL + "spells/treeShape.html",
  "tree stride":                             baseHelpURL + "spells/treeStride.html",
  "true resurrection":                   baseHelpURL + "spells/trueResurrection.html",
  "true seeing":                             baseHelpURL + "spells/trueSeeing.html",
  "true strike":                             baseHelpURL + "spells/trueStrike.html",
  "undeath to death":                    baseHelpURL + "spells/undeathtoDeath.html",
  "undetectable alignment":              baseHelpURL + "spells/undetectableAlignment.html",
  "unhallow":                                baseHelpURL + "spells/unhallow.html",
  "unholy aura":                             baseHelpURL + "spells/unholyAura.html",
  "unholy blight":                       baseHelpURL + "spells/unholyBlight.html",
  "unseen servant":                          baseHelpURL + "spells/unseenServant.html",
  "vampiric touch":                          baseHelpURL + "spells/vampiricTouch.html",
  "veil":                                    baseHelpURL + "spells/veil.html",
  "ventriloquism":                       baseHelpURL + "spells/ventriloquism.html",
  "virtue":                                  baseHelpURL + "spells/virtue.html",
  "vision":                                  baseHelpURL + "spells/vision.html",
  "wail of the banshee":                 baseHelpURL + "spells/wailoftheBanshee.html",
  "wall of fire":                        baseHelpURL + "spells/wallofFire.html",
  "wall of force":                       baseHelpURL + "spells/wallofForce.html",
  "wall of ice":                             baseHelpURL + "spells/wallofIce.html",
  "wall of iron":                        baseHelpURL + "spells/wallofIron.html",
  "wall of stone":                       baseHelpURL + "spells/wallofStone.html",
  "wall of thorns":                          baseHelpURL + "spells/wallofThorns.html",
  "warp wood":                           baseHelpURL + "spells/warpWood.html",
  "water breathing":                     baseHelpURL + "spells/waterBreathing.html",
  "water walk":                              baseHelpURL + "spells/waterWalk.html",
  "waves of exhaustion":                 baseHelpURL + "spells/wavesofExhaustion.html",
  "waves of fatigue":                    baseHelpURL + "spells/wavesofFatigue.html",
  "web":                                     baseHelpURL + "spells/web.html",
  "weird":                                   baseHelpURL + "spells/weird.html",
  "whirlwind":                           baseHelpURL + "spells/whirlwind.html",
  "whispering wind":                     baseHelpURL + "spells/whisperingWind.html",
  "wind walk":                           baseHelpURL + "spells/windWalk.html",
  "wind wall":                           baseHelpURL + "spells/windWall.html",
  "wish":                                    baseHelpURL + "spells/wish.html",
  "wood shape":                              baseHelpURL + "spells/woodShape.html",
  "word of chaos":                       baseHelpURL + "spells/wordofChaos.html",
  "word of recall":                          baseHelpURL + "spells/wordofRecall.html",
  "zone of silence":                     baseHelpURL + "spells/zoneofSilence.html",
  "zone of truth":                       baseHelpURL + "spells/zoneofTruth.html",


  '###last one###'   :           ""
};

